### ISSUE TITLE
Instructions for registry.neuvector.com

### ISSUE THREAD

**Issue by krumware** [neuvector/neuvector-helm#125]
The instructions still reflect dockerhub, which appears to longer be an option for image source.
Are there instructions for how to authenticate with registry.neuvector.com? The current instructions are unclear.

We would like to get the installation rolling in our Rancher deployment for evaluation. I've watched this video https://www.youtube.com/watch?v=cc8nA7nxuDc&t=79s, but it is old and does not address updated image pull or licensing methods.

**Comment by jorn-k** [comment]
Repo access for the images is granted by NeuVector employees at this time.

**Comment by becitsthere** [comment]
Pulling from NeuVector registry requires registration first. Please contact [support@neuvector.com](mailto:support@neuvector.com) get the license. Alternatively, you can use the open source preview images, listed here, https://github.com/neuvector/neuvector/blob/main/README.md
