### ISSUE TITLE
Unable to pull images from neuvector registry

### ISSUE THREAD

**Issue by felipemeamaral** [neuvector/neuvector-helm#139]
I'm currently trying to setup neuvector on my cluster but am unable to run it because now the images are hosted on a private registry.

```
neuvector                 neuvector-manager-pod-65dbb6448b-rmmm5           0/1     ErrImagePull       0          41s
neuvector                 neuvector-controller-pod-5d8b549c4c-vjw52        0/1     ErrImagePull       0          41s
neuvector                 neuvector-controller-pod-5d8b549c4c-lh8jr        0/1     ErrImagePull       0          41s
neuvector                 neuvector-scanner-pod-7bccc444d-ht4ns            0/1     ErrImagePull       0          41s
neuvector                 neuvector-enforcer-pod-klpw8                     0/1     ErrImagePull       0          41s
neuvector                 neuvector-controller-pod-5d8b549c4c-lbtl8        0/1     ErrImagePull       0          41s
neuvector                 neuvector-scanner-pod-7bccc444d-gdg2s            0/1     ErrImagePull       0          41s
neuvector                 neuvector-scanner-pod-7bccc444d-h9kxr            0/1     ErrImagePull       0          41s
```

How can I create an user on neuvector registry so that I can try the solution before buying it out?

BTW, documentation is completely outdated and it's doesn't reflect those steps required to set it up.
https://docs.neuvector.com/deploying/rancher

**Comment by cesar-souza** [comment]
Tambem tentei e não obtive sucesso !

**Comment by becitsthere** [comment]
Pulling from NeuVector registry requires registration first. Please contact support@neuvector.com get the license. Alternatively, you can use the open source preview images, listed here, https://github.com/neuvector/neuvector/blob/main/README.md
