### ISSUE TITLE
Permission "artifactregistry.repositories.downloadArtifacts" documentation

### ISSUE THREAD

**Issue by korenlev** [neuvector/neuvector-helm#148]
denied: Permission "artifactregistry.repositories.downloadArtifacts" denied

user credentials for docker are fine for many repos

need to document a step to register somewhere else ?

**Comment by becitsthere** [comment]
By default the images are set to neuvector registry for now. If you want to purchase the product, please contact our sales team. For testing purpose, we suggest you to modify the values.yaml and use the preview images.
