### ISSUE TITLE
Wrong registry, Wrong tags, tag 4.4.4 is hardcoded somewhere

### ISSUE THREAD

**Issue by achede22** [neuvector/neuvector-helm#149]
In your own [manual](https://open-docs.neuvector.com/deploying/kubernetes#important-notice-for-preview-version-users) itś said that I must:

The right image tags are:
- neuvector/manager.preview:5.0.0-preview.3
- neuvector/controller.preview:5.0.0-preview.3
- neuvector/enforcer.preview:5.0.0-preview.3
- neuvector/scanner.preview:latest
- neuvector/updater.preview:latest

The HELM repo should work well with the default values, but this is not happening here,  everyone should: 
- Update the registry to docker.io
- Update image names/tags to the preview version on Docker hub, as shown above
- Leave the imagePullSecrets empty

Even updating the tags, the HELM adds 4.4.4 that is hardcoded somewhere and the POD can´t pull the image.

default values.yaml file is wrong, 
The step-by-step in the [README](https://github.com/neuvector/neuvector-helm/blob/master/README.md) file is wrong, requesting to create a docker-registry secret and add it in --set imagePullSecrets=regsecret, when the manual said to leave it empty.

It seems that there is No way to make this HELM works.

**Comment by becitsthere** [comment]
4.4.4 is the latest official released version. Users should change the values.yaml to specify the version that they want to deploy.
