### ISSUE TITLE
accept license, set admin password

### ISSUE THREAD

**Issue by nauni77** [neuvector/neuvector-helm#153]
If you install neuvector with this helmchart you first have to login with default user/pwd admin:admin _and_ accept the license.

It would be nice to set the default admin password inside the helmchart. I didn't find a solution for this.

Running neuvector with this helm charts and _without_ RWX causes a downtime of the controller. Because only one controller can be used with this RWO-PVC and this needs to be shutdown before running the new one.

After this controller is up again the users, pwds, ... are still there - but you have to accept the license again. This happens if the packages of the nodes will be updated every night (including a restart of the nodes) - every day we have to accept the license. This is annoying.

It would be great if you can accept the license with the helm chart (other products do this) or make this accept persistent that it is only accepted once.

Thanks and best regards, Oli

**Comment by becitsthere** [comment]
Password can be set through ConfigMap, which can be included in helm chart.

**Comment by lindhe** [comment]
> ConfigMap

Unacceptable! Does it work via a Secret too?

**Comment by KeithMnemonic** [comment]
It is a secret. 

https://github.com/neuvector/neuvector-helm/blob/master/charts/core/values.yaml#L256

but you need to set an env variable as well ib the controller

https://github.com/neuvector/neuvector-helm/blob/master/charts/core/templates/controller-deployment.yaml#L143
