### ISSUE TITLE
Can't install Neuvector in Kubernetes with Helm or Helmfile.

### ISSUE THREAD

**Issue by naitmare01** [neuvector/neuvector-helm#188]
Im on [Azure Kuberentes Service](https://docs.microsoft.com/en-us/azure/aks/).

Steps to reproduce.

1. `helm repo add neuvector https://neuvector.github.io/neuvector-helm/`
2. `kubectl create namespace neuvector`
3. `helm install neuvector neuvector/core --version 2.2.2 --set tag=5.0.2 --set registry=docker.io --namespace neuvector`

> Note that we tried with `--version 2.2.0 and --set-tag=5.0.0` as per this blog post: https://blog.krum.io/deploying-neuvector/ and got the same result.

> Note that we also tried with `Helmfile` instead of `Helm` and got the same result as well.

Output from `kubectl -n neuvector get pods`

```
NAME                                        READY   STATUS    RESTARTS     AGE
neuvector-controller-pod-5bcffbf9ff-r5g6v   0/1     Error     1 (3s ago)   4s
neuvector-controller-pod-5bcffbf9ff-tpx89   0/1     Error     1 (3s ago)   4s
neuvector-controller-pod-5bcffbf9ff-xgrpp   0/1     Error     1 (3s ago)   4s
neuvector-manager-pod-9cb6c586d-b6vc7       1/1     Running   0            23m
neuvector-scanner-pod-d79fb9b77-bbcpx       1/1     Running   0            23m
neuvector-scanner-pod-d79fb9b77-dlc9d       1/1     Running   0            23m
neuvector-scanner-pod-d79fb9b77-hrsbt       1/1     Running   0            23m
```

Events from `kubectl -n neuvector describe pod neuvector-controller-pod*`

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  50s               default-scheduler  Successfully assigned neuvector/neuvector-controller-pod-5bcffbf9ff-r5g6v to aks-default-19655508-vmss00000d
  Normal   Pulled     9s (x4 over 50s)  kubelet            Container image "docker.io/neuvector/controller:5.0.2" already present on machine
  Normal   Created    9s (x4 over 50s)  kubelet            Created container neuvector-controller-pod
  Normal   Started    9s (x4 over 50s)  kubelet            Started container neuvector-controller-pod
  Warning  BackOff    5s (x7 over 48s)  kubelet            Back-off restarting failed container
```

Logs from `kubectl -n neuvector logs neuvector-controller-pod*`

```
2022-09-08T14:15:05|MON|/usr/local/bin/monitor starts, pid=1
2022-09-08T14:15:05|MON|Start ctrl, pid=8
2022-09-08T14:15:05.311|INFO|CTL|main.main: START - version=v5.0.2
2022-09-08T14:15:05.311|INFO|CTL|main.main: - join=neuvector-svc-controller.neuvector
2022-09-08T14:15:05.311|INFO|CTL|main.main: - advertise=10.244.3.215
2022-09-08T14:15:05.312|INFO|CTL|main.main: - bind=10.244.3.215
2022-09-08T14:15:05.315|INFO|CTL|system.NewSystemTools: cgroup v1
2022-09-08T14:15:05.315|INFO|CTL|container.Connect: - endpoint=
2022-09-08T14:15:05.315|ERRO|CTL|main.main: Failed to initialize - error=Unknown container runtime
2022-09-08T14:15:05|MON|Process ctrl exit status 254, pid=8
2022-09-08T14:15:05|MON|Process ctrl exit with non-recoverable return code. Monitor Exit!!
Leave the cluster
Error leaving: Put "http://127.0.0.1:8500/v1/agent/leave": dial tcp 127.0.0.1:8500: connect: connection refused
2022-09-08T14:15:05|MON|Clean up.
```

When we do a port-forward like `kubectl port-forward --namespace neuvector service/neuvector-service-webui 8443` we can go to the portal at https://localhost:8443 but we are greeted with `Controller is not available ... ` and when we try to login we get `Network connect timeout error `.

What is next step for us?
![Screenshot 2022-09-08 at 16 17 41](https://user-images.githubusercontent.com/11064669/189146800-6c256cce-57ab-418e-9868-056f22641066.png)
![Screenshot 2022-09-08 at 16 20 23](https://user-images.githubusercontent.com/11064669/189146805-45c72cda-13a6-4e44-b1c0-86649353bc4f.png)

**Comment by lindhe** [comment]
I can reproduce this in a local k3s cluster.

**Comment by naitmare01** [comment]
@mjnagel your issues does look a lot like @lindhe. 
Are you able to reproduce it in a Kuberentes-environment?

**Comment by mjnagel** [comment]
@naitmare01 what type of cluster are you on? I've only tried on k3d so far but plan to test on k3s as well (and I expect to see better results).

**Comment by naitmare01** [comment]
Im on [Azure Kuberentes Service](https://docs.microsoft.com/en-us/azure/aks/).

**Comment by bashofmann** [comment]
AKS is now using containerd and not Docker/moby anymore as a container runtime: https://azure.microsoft.com/de-de/updates/azure-kubernetes-service-aks-support-for-containerd-runtime-is-in-preview/.

When installing NeuVector, you have to tell where and how NeuVector can connect to the container runtime. The default value is a Docker socket at `/var/run/docker.sock`.

For AKS with containerd, you have to set:

`--set containerd.enabled=true` which will configure it for a containerd socket at `/var/run/containerd/containerd.sock` (see also https://github.com/neuvector/neuvector-helm/blob/master/charts/core/values.yaml#L347).

Then the controller will successfully come up. I just tested it with AKS v1.23.8.

**Comment by naitmare01** [comment]
Setting `--set containerd.enabled=true` did the trick for us as well.

**Comment by avi1512** [comment]
Having same issue with neuvector controller and enforcer pod is not coming up. After upgrade the helm values with --set containerd.enabled=true is came up and running.. Thanks @bashofmann
