### ISSUE TITLE
Neuvector Helm-created CRDs get Reconciled by App, Breaks GitOps Sync

### ISSUE THREAD

**Issue by atoy3731** [neuvector/neuvector-helm#241]
## Issue

When deploying Neuvector through GitOps (in my case, Fleet) and leveraging either the `crd` chart or having `crdwebhook.enabled=false` in the `core` chart, the chart will successfully create the CRDs, however when the controller starts running, it checks for the existence of Roles, and when they exist, the controller overwrites the CRDs, wiping out the annotations/labels used by GitOps/Fleet to track the resources. This causes it to go out of sync, with no way to reconcile it.

## Proposed Solution

There's a few ways this could be solved:

1. Remove CRD creation from the chart(s), have the roles attached to the controller, and have the controller solely responsible for the management of CRDs.
2. Remove CRD management from the controller itself, have it solely managed by the chart(s).
3. Separate the chart CRDs from the Roles, so someone can install the CRDs from the chart without creating the roles. This will give users the ability to manage the CRDs purely from the chart without the controller overwriting them.

**Comment by becitsthere** [comment]
This is fixed in 5.1.3. The product will not change the deployed CRD.
