### ISSUE TITLE
Wrong network rules learned

### ISSUE THREAD

**Issue by qmaraval-csgroup** [neuvector/neuvector-helm#251]
Hello, 
I am currently testing Neuvector on a 1.23 CCE kubernetes cluster.
I noticed weirds links between pods in Network activity and rules learned.
In order to test, i deployed one pod and ran a curl to others pods and it seems that Neuvector detects it with the right ip src and ip dst port, but links it to the wrong application pods and doing so generates wrong networks rules ...
I tried to change neuvector versions but even with 5.1.0 the issue remains.

I am quite surprised because i tested it with another cluster (not CCE) and it works perfectly ...
Did i miss something in my configuration or is it linked to CCE kubernetes clusters ?

Thanks.

**Comment by becitsthere** [comment]
Please report product issues in neuvector repo.
