### ISSUE TITLE
Consider publishing chart

### ISSUE THREAD

**Issue by timwebster9** [neuvector/neuvector-helm#28]
It would be nice if this chart was published in a chart repository.  We would prefer to use your 'official' chart rather than maintaining our own because:

-  we would be more confident we are using it as intended
-  we would like to add custom features, but instead of adding them as PRs, we would prefer to make this chart a dependency in our own chart (i.e. via `requirements.yaml` because they are specific to our environment.) . However to do this the chart must be published, not a Github clone.

Also we considered publishing ourselves, but the chart name doesn't match the directory name:

```
Tims-MBP-4:neuvector-helm timw$ helm package .
Error: directory name (neuvector-helm) and Chart.yaml name (neuvector) must match
```

EDIT - nevermind the last comment - cloning to a directory called `neuvector` will fix this...

**Comment by timja** [comment]
@garyduan any chance this could be published to a chart repo?

**Comment by christianhuening** [comment]
would also love to see that done!

**Comment by apeschel** [comment]
It's a little early, but heck, happy birthday to this issue! Hopefully this year, you can get a response from the developers!

🎂

**Comment by becitsthere** [comment]
The helm chart has been published. You can use the following command to install charts

`
helm repo add neuvector https://neuvector.github.io/neuvector-helm/
helm search neuvector/core
helm install --name my-release --namespace neuvector neuvector/core 
`

Please see the helm chart source code repo ([https://github.com/neuvector/neuvector-helm](https://github.com/neuvector/neuvector-helm)) for details.
