### ISSUE TITLE
Use a `$datasource` variable in the Grafana dashboard.

### ISSUE THREAD

**Issue by ikogan** [neuvector/neuvector-helm#349]
Currently, each panel in the Grafana dashboard uses a hardcoded datasource uid of `datasource`. In our Grafana, we use `Prometheus`. This means that the dashboard doesn't work unless we manually modify each panel. If the dashboard used a variable instead _and_ it didn't match our instance, we could simply pick from the dropdown.

The delivered Rancher dashboards use a template variable like this:

```json
  "templating": {
    "list": [
      {
        "current": {
          "text": "Prometheus",
          "value": "Prometheus"
        },
        "hide": 0,
        "label": "Data Source",
        "name": "datasource",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      }
    ]
  }
```

Each panel then just references the `$datasource` variable.

**Comment by becitsthere** [comment]
Thanks for raising the issue and making the improvements.
