### ISSUE TITLE
Someone renamed the chart

### ISSUE THREAD

**Issue by wzrdtales** [neuvector/neuvector-helm#65]
Someone renamed the chart to "core". Please don't do that and break all running deployments...

**Comment by becitsthere** [comment]
The change is made in PR #63, the change allows us to publish the chart so the user doesn't need to clone the source, but to use our published helm repo. With the directory structure change, we will be able to add more charts in the future.

At the end of the README.md file, we talked about how to migrate from the previous chart.

We are sorry this change breaks your workflow. Please let us know if you have any issue with the new chart structure.

**Comment by wzrdtales** [comment]
It doesn't break a workflow. It breaks *production systems*, introducing breaking changes without a second thought and without caring at all for your customers is not acceptable. It create costs on the customer side who don't know how to handle this, just to hire a consultant which costs them money. 101 of maintenance is announcing changes way before they happen, at least half a year before and doing this over an appropriate channel. You should have never touched this repo at all, but instead create a new one.
